/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mynotes;

import java.util.List;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.json.JSONObject;

/**
 *
 * @author andresbenitez
 */
public class frmFindList extends javax.swing.JFrame {
    static globalDataArea gDatos;
    List<String> listCatID = new ArrayList<>();

    /**
     * Creates new form frmFindList
     * @param m
     */
    public frmFindList(globalDataArea m) throws SQLException {
        initComponents();
        gDatos = m;
        

        DefaultListModel dlm = new DefaultListModel();
        this.jList1.setModel(dlm);
        dlm.clear();

        /*
            Se conecta a BD para traer datos
        */
        oracleDB conn = new oracleDB();
        conn.setDbName("oratest");
        conn.setDbUser("notes");
        conn.setDbPass("notes01");
        conn.setHostIp("oradb01");
        conn.setDbPort("1521");
        
        conn.conectar();
        
        if (conn.getConnStatus()) {
            String vSQL="select catID, catDesc from nt_category where lower(catDesc) like lower('%"+gDatos.getCmdMenu()+"%')";
            ResultSet rs = conn.consultar(vSQL);
            if (rs!=null) {
                while (rs.next()) {
                    listCatID.add(rs.getString("catID"));
                    dlm.addElement(rs.getString("catDesc"));
                }
            }
            conn.closeConexion();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorías");
        setAlwaysOnTop(true);
        setResizable(false);

        jList1.setBackground(java.awt.Color.black);
        jList1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jList1.setForeground(new java.awt.Color(204, 255, 204));
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                // Enter was pressed. Your code goes here.
                gDatos.setCatID(listCatID.get(this.jList1.getSelectedIndex()));
                frmFindItems frmItems;
                try {
                    frmItems = new frmFindItems(gDatos);
                    frmItems.show();
                } catch (SQLException ex) {
                    Logger.getLogger(myNote.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if(evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
                this.dispose();
            }
            

    }//GEN-LAST:event_jList1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFindList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFindList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFindList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFindList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new frmFindList(gDatos).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmFindList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
